- name: apt update & full-upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: full

- name: sudo no password
  become: yes
  lineinfile:
    path: /etc/sudoers
    line: "{{ ansible_ssh_user }} ALL=NOPASSWD: ALL"
    insertafter: "%sudo   ALL=(ALL:ALL) ALL"