- name: mkdir .ssh
  become: yes
  file: dest=/home/{{ ansible_ssh_user }}/.ssh/ state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}

- name: generate ssh-key
  become: yes
  openssh_keypair:
    path: /home/{{ ansible_ssh_user }}/.ssh/id_ed25519
    type: ed25519